stats : scipy_conf_stats.py name_class.py scipy_conf_parsers.py
	rm -f stats
	./scipy_conf_stats.py 2002 | grep '##' >> /tmp/scipy.stats
	./scipy_conf_stats.py 2003 | grep '##' >> /tmp/scipy.stats
	./scipy_conf_stats.py 2004 | grep '##' >> /tmp/scipy.stats
	./scipy_conf_stats.py 2005 | grep '##' >> /tmp/scipy.stats
	./scipy_conf_stats.py 2006 | grep '##' >> /tmp/scipy.stats
	./scipy_conf_stats.py 2007 | grep '##' >> /tmp/scipy.stats
	./scipy_conf_stats.py 2008 | grep '##' >> /tmp/scipy.stats
	./scipy_conf_stats.py 2009 | grep '##' >> /tmp/scipy.stats
	./scipy_conf_stats.py 2010 | grep '##' >> /tmp/scipy.stats
	./scipy_conf_stats.py 2011 | grep '##' >> /tmp/scipy.stats
	./scipy_conf_stats.py 2014 | grep '##' >> /tmp/scipy.stats
	./scipy_conf_stats.py 2015 | grep '##' >> /tmp/scipy.stats
	./scipy_conf_stats.py 2016 | grep '##' >> /tmp/scipy.stats
	./scipy_conf_stats.py 2017 | grep '##' >> /tmp/scipy.stats
